# Generated by Django 4.1.5 on 2023-02-07 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ubicacion', models.TextField()),
                ('areatotal', models.IntegerField()),
                ('areaconstruida', models.IntegerField()),
                ('cantdedormitorios', models.IntegerField()),
                ('hayasensor', models.BooleanField()),
                ('descuento', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('estadodepredio', models.IntegerField(choices=[(1, 'En construccion'), (2, 'En planos'), (3, 'Departamento'), (4, 'Casa'), (5, 'Terreno')], default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('imagenprincipal', models.ImageField(null=True, upload_to='images/')),
                ('imagensecundaria00', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria01', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria02', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria03', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria04', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria05', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria06', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria07', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria08', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria09', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria10', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagensecundaria11', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
