# Generated by Django 4.1.5 on 2023-02-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='estadodepredio',
        ),
    ]
