# Generated by Django 4.1.5 on 2023-02-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_preciodolares'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cantdebaños',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
